<?php if ($content = $block->getContent('popup-content')) { ?>

    <div id="modal-overlay" style="display:none; padding: 5%; text-align: center; background-color: bisque; font-size: 16px;">
        <?php echo $content ?>
    </div>
    <script type="text/x-magento-init">
        {
            "*": {
                "Magento_Ui/js/core/app": {
                    "components": {
                        "modal_overlay": {
                            "component": "Popup_ModalOverlay/js/modal_overlay"
                        }
                     }
                }
            }
        }
    </script><?php } ?>